config/routes.rb
Rails.application.routes.draw do
  get 'git_http/show'

  resources :widgets

  get 'taco_order/edit'

  get 'hello_angular/show'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  validates :price, presence: true, numericality: { greater_than: 10 }
  validates :name, presence: true, length: { minimum: 7 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/git_http_controller.rb
class GitHttpController < ApplicationController
  def show
  end
end

app/controllers/hello_angular_controller.rb
class HelloAngularController < ApplicationController
  def show
  end
end

app/controllers/taco_order_controller.rb
class TacoOrderController < ApplicationController
  def edit
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render json: @widget, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/git_http_helper.rb
module GitHttpHelper
end

app/helpers/hello_angular_helper.rb
module HelloAngularHelper
end

app/helpers/taco_order_helper.rb
module TacoOrderHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/git_http/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="GitHttpController">
  <div class="col-md-6">
    <h1>Git $http</h1>
      <form ng-submit="search()">
        <div class="input-group">
          <span class="input-group-addon">
            <i class="icon-search"></i>
          </span>
          <input type="text" class="form-control" placeholder="Git Username" ng-model="username">
        </div>
      </form>

      <hr />

      <ul class="list-group">
        <li class="list-group-item" ng-repeat="repo in repos">
          <h4 class="list-group-item-heading">{{ repo.full_name }}</h4>
          <p class="list-group-item-text text-muted">{{ repo.url }}</p>
        </li>
      </ul>
  </div>
</div>

app/views/hello_angular/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="HelloWorldController">
  <div class="col-md-6">
    <h1>Hello AngularJS</h1>
    <p>Type in the input box and watch as AngularJS updates the property through the magic of binding.</p>
    <input type="text" class="form-control" ng-model="myText">
      {{ myText }}
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Angularails"  %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="container">
      <a class="navbar-brand" href="#">Angularails</a>
    </div>
  </div>

  <div class="container">

<%= yield %>

  </div>
</body>
</html>

app/views/taco_order/edit.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="TacoOrderController">

  

  <div class="col-md-6">
    <h3>Add Taco to Order</h3>

    <form ng-submit="addTaco()">

      <div class="form-group">
        <label for="name=">Name your creation</label>
        <input type="text" class="form-control" placeholder="Super Tasty" ng-model="taco.name"></input>
      </div>

      <div class="form-group">

        <label for="filling">Select your filling</label>

        <select ng-model="taco.filling" class="form-control", ng-options="f for f in fillings">
          <option value="">Pick a filling</option>
      </select>
      </div>

      <div class="form-group">
        <label>Extras</label>
        <div class="checkbox" ng-repeat="extra in extras">
          <label>
            <input type="checkbox" ng-model="extra.checked"></input>
              {{ extra.name }}
          </label>
        </div>
      </div>

      <div class="form-group">
        <label>Cheese</label>
          <div class="radio" ng-repeat="cheese in cheeses">
            <label>
              <input type="radio" value="{{ cheese }}" ng-model="taco.cheese"></input>
              {{ cheese }}
            </label>
          </div>
      </div>

        
      <button class="btn btn-primary">
        Submit
      </button>
    </form>

  </div>

  <div class="col-md-6">
    <h3>Your Order</h3>

    <table class="table">
      <tbody>
        <tr ng-repeat="taco in tacos">
          <td>{{ taco.name }}</td>
          <td>{{ taco.filling }}</td>
          <td>
            <span ng-repeat="extra in taco.extras">
              {{ extra }}
          </td>
          <td>{{ taco.cheese }}</td>
        </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/widgets/_form.html.erb
<div ng-app="AngulaRails">
  <%= form_for @widget, id: "widgetForm", html: { name: "widgetForm", "novalidate" => true } do |f|  %>
  <% if @widget.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(@widget.errors.count, "error")  %></h4>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[name]'].$invalid }">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", "ng-model" => "name", required: true  %>
    <span class="help-block" ng-show="widgetForm]'widget[name]'].$error.required">Required</span>
  </div>

  <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[price]'].$invalid }">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control", "ng-model" => "price", required: true, "min" => "10" %>

    <span class="help-block" ng-show="widgetForm]'widget[name]'].$error.required">Must be greater than 10</span>
  </div>
    <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @widget.price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>